<?php

namespace App\Services;

use App\Models\NotasFiscaisSaida;
use Illuminate\Support\Facades\DB;

class NotaFiscaisSaidaService {

    const NOME_CONFIGURACOES = 'change_tracking_notas_fiscais_saida';
    const NOME_CONFIGURACOES_COMPLEMENTO = 'change_tracking_notas_fiscais_saida_complemento';

    /**
     * busca as ultimas modificações da tabela no ERP
     */
    public static function getLastChagingTrackingERP($lastVersion) {

        $dados = DB::connection('sqlsrv_ERP')->select(
                "SELECT
                    nf.numnota,
                    nf.serie,
                    nf.codclie,
                    nf.dtemis,
                    nf.espdoc,
                    nf.filial,
                    nf.estado,
                    nf.cfo,
                    nf.tpo,
                    nf.valcontab,
                    nf.baseicm,
                    nf.baseicm2,
                    nf.baseicm3,
                    nf.alqicm,
                    nf.alqicm2,
                    nf.alqicm3,
                    nf.valicm,
                    nf.valicm2,
                    nf.valicm3,
                    nf.baseipi,
                    nf.valipi,
                    nf.valsemicm,
                    nf.valsemipi,
                    nf.basestrib,
                    nf.valsubstri,
                    nf.valtribdif,
                    nf.destaqipi,
                    nf.valservico,
                    nf.valiss,
                    nf.valfrete,
                    nf.valseguro,
                    nf.freteinc,
                    nf.outricm,
                    nf.outripi,
                    nf.ccusto,
                    nf.obs,
                    nf.codvend,
                    CASE
                        WHEN (p.referencia is not null) AND (p.referencia <> '') AND (p.referencia <> ' ')  
                            THEN p.referencia
                        ELSE CAST(p.numped AS VARCHAR(100))
                    END AS pedido_id,
                    nf.numped,
                    nf.valentrad,
                    nf.codmetra,
                    nf.codtran,
                    nf.desconto,
                    nf.comissao,
                    ct.numord,
                    nf.faturado,
                    nf.atualiz,
                    nf.flagemit,
                    nf.flagregfis,
                    nf.flagatua,
                    nf.icmsipi,
                    nf.valemba,
                    nf.codrote,
                    nf.codnatop,
                    nf.filtransf,
                    nf.tiponf,
                    nf.flaginter,
                    nf.flagcontab,
                    nf.codsitest,
                    nf.codsitfed,
                    nf.percsubst,
                    nf.lucro,
                    nf.rec,
                    nf.cxa,
                    nf.flu,
                    nf.ctb,
                    nf.atf,
                    nf.cus,
                    nf.integrado,
                    nf.dtcancel,
                    nf.baseiss,
                    nf.modelonf,
                    nf.condpag,
                    nf.est,
                    nf.lif,
                    nf.fat,
                    nf.exportado,
                    nf.codmes,
                    nf.peripi,
                    nf.localporta,
                    nf.conta,
                    nf.codtran2,
                    nf.cupomini,
                    nf.cupomfim,
                    nf.gve,
                    nf.baseicm4,
                    nf.alqicm4,
                    nf.valicm4,
                    nf.clasvend,
                    nf.flagcons,
                    nf.clifim,
                    nf.exporta,
                    nf.pedimpo,
                    nf.tiponota,
                    nf.numecf,
                    nf.numcupon,
                    nf.valnfche,
                    nf.clientea,
                    nf.nordven,
                    nf.numnfecf,
                    nf.baseicm5,
                    nf.alqicm5,
                    nf.valicm5,
                    nf.numordfis,
                    nf.impoger,
                    nf.icmsfonte,
                    nf.totmerc,
                    nf.totpeso,
                    nf.txfinan,
                    nf.exced,
                    nf.codlis,
                    nf.oiddocdeorigem,
                    nf.atuacum,
                    nf.jacomis,
                    nf.Contabilizado,
                    nf.codforout,
                    nf.deporigem,
                    nf.tpooutraent,
                    nf.contredz,
                    nf.gt,
                    nf.BaseIR,
                    nf.AliqIR,
                    nf.codger,
                    nf.OIDREVENDA,
                    nf.Historico,
                    nf.BaseINSS,
                    nf.AliqINSS,
                    nf.ValINSS,
                    nf.AliqISSRet,
                    nf.BaseISSRet,
                    nf.ValISSRet,
                    nf.ValIRRF,
                    nf.NFFutura,
                    nf.NOrdExpedic,
                    nf.validade,
                    nf.sitproduto,
                    nf.DESPNAOINCLUSAS,
                    nf.ICMSDESPNAOINCLUSAS,
                    nf.FRETESUBSTRIBUTARIA,
                    nf.SerieECF,
                    nf.GTFim,
                    nf.ValCanECF,
                    nf.ValDescECF,
                    nf.ContReiOpe,
                    nf.OUTRASDESPESASINCLUSAS,
                    nf.TipoEntr,
                    nf.NUMORDECF,
                    nf.TOTALPRECOCOMICMS,
                    nf.TOTALVALORICMS,
                    nf.DESPESASIMPORTACAO,
                    nf.oidserialecf,
                    ct.SYS_CHANGE_OPERATION AS 'last_operation',
                    COALESCE(tc.commit_time, GETDATE()) AS 'last_commit_time'
           FROM CHANGETABLE (CHANGES [NFSAIDACAD], :lastVersion) AS ct
           LEFT JOIN sys.dm_tran_commit_table tc on ct.sys_change_version = tc.commit_ts
           LEFT JOIN NFSAIDACAD nf on nf.numord = ct.numord
           LEFT JOIN PEDICLICAD p on p.numped = nf.numped", ['lastVersion' => $lastVersion]);
        return json_decode(json_encode($dados), true);
    }

    /**
     * inserir/update os dados de nota fiscal
     */
    public static function flushINotaFiscal($dados) {

        NotasFiscaisSaida::upsert($dados, ['numord'],
                [
                    "numnota",
                    "serie",
                    "codclie",
                    "dtemis",
                    "espdoc",
                    "filial",
                    "estado",
                    "cfo",
                    "tpo",
                    "valcontab",
                    "baseicm",
                    "baseicm2",
                    "baseicm3",
                    "alqicm",
                    "alqicm2",
                    "alqicm3",
                    "valicm",
                    "valicm2",
                    "valicm3",
                    "baseipi",
                    "valipi",
                    "valsemicm",
                    "valsemipi",
                    "basestrib",
                    "valsubstri",
                    "valtribdif",
                    "destaqipi",
                    "valservico",
                    "valiss",
                    "valfrete",
                    "valseguro",
                    "freteinc",
                    "outricm",
                    "outripi",
                    "ccusto",
                    "obs",
                    "codvend",
                    "pedido_id",
                    "numped",
                    "valentrad",
                    "codmetra",
                    "codtran",
                    "desconto",
                    "comissao",
                    "numord",
                    "faturado",
                    "atualiz",
                    "flagemit",
                    "flagregfis",
                    "flagatua",
                    "icmsipi",
                    "valemba",
                    "codrote",
                    "codnatop",
                    "filtransf",
                    "tiponf",
                    "flaginter",
                    "flagcontab",
                    "codsitest",
                    "codsitfed",
                    "percsubst",
                    "lucro",
                    "rec",
                    "cxa",
                    "flu",
                    "ctb",
                    "atf",
                    "cus",
                    "integrado",
                    "dtcancel",
                    "baseiss",
                    "modelonf",
                    "condpag",
                    "est",
                    "lif",
                    "fat",
                    "exportado",
                    "codmes",
                    "peripi",
                    "localporta",
                    "conta",
                    "codtran2",
                    "cupomini",
                    "cupomfim",
                    "gve",
                    "baseicm4",
                    "alqicm4",
                    "valicm4",
                    "clasvend",
                    "flagcons",
                    "clifim",
                    "exporta",
                    "pedimpo",
                    "tiponota",
                    "numecf",
                    "numcupon",
                    "valnfche",
                    "clientea",
                    "nordven",
                    "numnfecf",
                    "baseicm5",
                    "alqicm5",
                    "valicm5",
                    "numordfis",
                    "impoger",
                    "icmsfonte",
                    "totmerc",
                    "totpeso",
                    "txfinan",
                    "exced",
                    "codlis",
                    "oiddocdeorigem",
                    "atuacum",
                    "jacomis",
                    "Contabilizado",
                    "codforout",
                    "deporigem",
                    "tpooutraent",
                    "contredz",
                    "gt",
                    "BaseIR",
                    "AliqIR",
                    "codger",
                    "OIDREVENDA",
                    "Historico",
                    "BaseINSS",
                    "AliqINSS",
                    "ValINSS",
                    "AliqISSRet",
                    "BaseISSRet",
                    "ValISSRet",
                    "ValIRRF",
                    "NFFutura",
                    "NOrdExpedic",
                    "validade",
                    "sitproduto",
                    "DESPNAOINCLUSAS",
                    "ICMSDESPNAOINCLUSAS",
                    "FRETESUBSTRIBUTARIA",
                    "SerieECF",
                    "GTFim",
                    "ValCanECF",
                    "ValDescECF",
                    "ContReiOpe",
                    "OUTRASDESPESASINCLUSAS",
                    "TipoEntr",
                    "NUMORDECF",
                    "TOTALPRECOCOMICMS",
                    "TOTALVALORICMS",
                    "DESPESASIMPORTACAO",
                    "oidserialecf",
                    "last_operation",
                    "last_commit_time"
        ]);
    }

    /**
     * busca as ultimas modificações da tabela no ERP
     */
    public static function getLastChagingTrackingERPcomplementosNF($lastVersion) {

        $dados = DB::connection('sqlsrv_ERP')->select(
                "SELECT
                    c.baseicmdestacado as comp_nf_saida_baseicmdestacado,
                    c.codigoregiao as comp_nf_saida_codigoregiao,
                    c.consultasuframa as comp_nf_saida_consultasuframa,
                    c.cotacaomoeda as comp_nf_saida_cotacaomoeda,
                    c.expedidor as comp_nf_saida_expedidor,
                    c.fretepagar as comp_nf_saida_fretepagar,
                    c.gerarnfservico as comp_nf_saida_gerarnfservico,
                    c.kmatual as comp_nf_saida_kmatual,
                    c.kmmes as comp_nf_saida_kmmes,
                    c.moeda as comp_nf_saida_moeda,
                    c.motorista as comp_nf_saida_motorista,
                    ct.numord,
                    c.numordnfvenda as comp_nf_saida_numordnfvenda,
                    c.numordprodproprio as comp_nf_saida_numordprodproprio,
                    c.numpedregional as comp_nf_saida_numpedregional,
                    c.oidcontratante as comp_nf_saida_oidcontratante,
                    c.percentualcofins as comp_nf_saida_percentualcofins,
                    c.percentualpis as comp_nf_saida_percentualpis,
                    c.percicmdestacado as comp_nf_saida_percicmdestacado,
                    c.placa as comp_nf_saida_placa,
                    c.previsaoentrega as comp_nf_saida_previsaoentrega,
                    c.responsavelconsulta as comp_nf_saida_responsavelconsulta,
                    c.situacaocadastrosuframa as comp_nf_saida_situacaocadastrosuframa,
                    c.statusconsignacao as comp_nf_saida_statusconsignacao,
                    c.tipofrete as comp_nf_saida_tipofrete,
                    c.valorfretedestacado as comp_nf_saida_valorfretedestacado,
                    c.valoricmfrete as comp_nf_saida_valoricmfrete,
                    c.classe as comp_nf_saida_classe,
                    c.codvendext as comp_nf_saida_codvendext,
                    c.itinerario as comp_nf_saida_itinerario,
                    c.manual as comp_nf_saida_manual,
                    c.markuprealtotal as comp_nf_saida_markuprealtotal,
                    c.numeroempenho as comp_nf_saida_numeroempenho,
                    c.numpedprodrel as comp_nf_saida_numpedprodrel,
                    c.ordem as comp_nf_saida_ordem,
                    c.unidadeexecutora as comp_nf_saida_unidadeexecutora,
                    c.valcustofrete as comp_nf_saida_valcustofrete,
                    c.valoricmsdispensado as comp_nf_saida_valoricmsdispensado,
                    c.aidf as comp_nf_saida_aidf,
                    c.observacao as comp_nf_saida_observacao,
                    c.recibonfe as comp_nf_saida_recibonfe,
                    c.chavedeacessonfe as comp_nf_saida_chavedeacessonfe,
                    c.situacaonfe as comp_nf_saida_situacaonfe,
                    c.numeroprotocolo as comp_nf_saida_numeroprotocolo,
                    c.codigonfe as comp_nf_saida_codigonfe,
                    c.lotenfe as comp_nf_saida_lotenfe,
                    c.justificativa as comp_nf_saida_justificativa,
                    c.flagemitcontingencia as comp_nf_saida_flagemitcontingencia,
                    c.filialnfe as comp_nf_saida_filialnfe,
                    c.finnfe as comp_nf_saida_finnfe,
                    c.numordcontingencia as comp_nf_saida_numordcontingencia,
                    c.numeroprotocolocancelamento as comp_nf_saida_numeroprotocolocancelamento,
                    c.numeroprotocoloinutilizacao as comp_nf_saida_numeroprotocoloinutilizacao,
                    c.recibodpec as comp_nf_saida_recibodpec,
                    c.dtemis as comp_nf_saida_dtemis,
                    c.dhprotocolo as comp_nf_saida_dhprotocolo,
                    c.dhrecibodpec as comp_nf_saida_dhrecibodpec,
                    c.dhcancelamento as comp_nf_saida_dhcancelamento,
                    c.redzmanual as comp_nf_saida_redzmanual,
                    c.flagpiscofins as comp_nf_saida_flagpiscofins,
                    c.valoracrescimo as comp_nf_saida_valoracrescimo,
                    c.ade_atodeclaratorio as comp_nf_saida_ade_atodeclaratorio,
                    c.ade_datadocumento as comp_nf_saida_ade_datadocumento,
                    c.ade_modelodocumento as comp_nf_saida_ade_modelodocumento,
                    c.ade_numerodocumento as comp_nf_saida_ade_numerodocumento,
                    c.ade_participante as comp_nf_saida_ade_participante,
                    c.ade_seriedocumento as comp_nf_saida_ade_seriedocumento,
                    c.codproconj as comp_nf_saida_codproconj,
                    c.descontodevolucao as comp_nf_saida_descontodevolucao,
                    c.descontosuframa as comp_nf_saida_descontosuframa,
                    c.etiquetaemitida as comp_nf_saida_etiquetaemitida,
                    c.flagpesoalterado as comp_nf_saida_flagpesoalterado,
                    c.isscidade as comp_nf_saida_isscidade,
                    c.nfeimportada as comp_nf_saida_nfeimportada,
                    c.numpedautomatico as comp_nf_saida_numpedautomatico,
                    c.oiddocdeorigemcomissao as comp_nf_saida_oiddocdeorigemcomissao,
                    c.oiddocdeorigemfrete as comp_nf_saida_oiddocdeorigemfrete,
                    c.percentualcomissao as comp_nf_saida_percentualcomissao,
                    c.quantconj as comp_nf_saida_quantconj,
                    c.ratendimento as comp_nf_saida_ratendimento,
                    c.recebimentotef as comp_nf_saida_recebimentotef,
                    c.usulibcancelamentonf as comp_nf_saida_usulibcancelamentonf,
                    c.valoricmfreteo as comp_nf_saida_valoricmfreteo,
                    c.totaltributo as comp_nf_saida_totaltributo,
                    c.dhemissao as comp_nf_saida_dhemissao,
                    c.cod_inf_compl as comp_nf_saida_cod_inf_compl,
                    c.des_inf_compl as comp_nf_saida_des_inf_compl,
                    c.flagrentabi as comp_nf_saida_flagrentabi,
                    c.valordescontopiscofins as comp_nf_saida_valordescontopiscofins,
                    c.flagcriacao as comp_nf_saida_flagcriacao,
                    c.dhinutilizaþòo as comp_nf_saida_dhinutilizaþòo,
                    c.chavecancelamentocfe as comp_nf_saida_chavecancelamentocfe,
                    c.regimeespecial as comp_nf_saida_regimeespecial,
                    c.fimfaixainutilizacao as comp_nf_saida_fimfaixainutilizacao,
                    c.dhcontingencia as comp_nf_saida_dhcontingencia,
                    c.justificativacontingencia as comp_nf_saida_justificativacontingencia,
                    c.filialusuario as comp_nf_saida_filialusuario,
                    c.rusuariocriacao as comp_nf_saida_rusuariocriacao,
                    c.predanfe as comp_nf_saida_predanfe,
                    c.linkimagemcanhoto as comp_nf_saida_linkimagemcanhoto,
                    c.entradaautomatica as comp_nf_saida_entradaautomatica,
                    c.entradaorigem as comp_nf_saida_entradaorigem,
                    c.flagdespinclusanaotributada as comp_nf_saida_flagdespinclusanaotributada,
                    c.enviadomensagem as comp_nf_saida_enviadomensagem,
                    c.dhinutilizacao as comp_nf_saida_dhinutilizacao,
                    ct.SYS_CHANGE_OPERATION AS last_operation,
                    COALESCE(tc.commit_time, GETDATE()) AS last_commit_time
           FROM CHANGETABLE (CHANGES [COMPLEMENTONFSAIDA], :lastVersion) AS ct
           LEFT JOIN sys.dm_tran_commit_table tc on ct.sys_change_version = tc.commit_ts
           LEFT JOIN COMPLEMENTONFSAIDA c on c.numord = ct.numord", ['lastVersion' => $lastVersion]);
        return json_decode(json_encode($dados), true);
    }

    /**
     * inserir/update os dados de complemento nota fiscal
     */
    public static function flushIComplementoNotaFiscal($dados) {

        NotasFiscaisSaida::upsert($dados, ['numord'],
                [
                    "comp_nf_saida_baseicmdestacado",
                    "comp_nf_saida_codigoregiao",
                    "comp_nf_saida_consultasuframa",
                    "comp_nf_saida_cotacaomoeda",
                    "comp_nf_saida_expedidor",
                    "comp_nf_saida_fretepagar",
                    "comp_nf_saida_gerarnfservico",
                    "comp_nf_saida_kmatual",
                    "comp_nf_saida_kmmes",
                    "comp_nf_saida_moeda",
                    "comp_nf_saida_motorista",
                    "numord",
                    "comp_nf_saida_numordnfvenda",
                    "comp_nf_saida_numordprodproprio",
                    "comp_nf_saida_numpedregional",
                    "comp_nf_saida_oidcontratante",
                    "comp_nf_saida_percentualcofins",
                    "comp_nf_saida_percentualpis",
                    "comp_nf_saida_percicmdestacado",
                    "comp_nf_saida_placa",
                    "comp_nf_saida_previsaoentrega",
                    "comp_nf_saida_responsavelconsulta",
                    "comp_nf_saida_situacaocadastrosuframa",
                    "comp_nf_saida_statusconsignacao",
                    "comp_nf_saida_tipofrete",
                    "comp_nf_saida_valorfretedestacado",
                    "comp_nf_saida_valoricmfrete",
                    "comp_nf_saida_classe",
                    "comp_nf_saida_codvendext",
                    "comp_nf_saida_itinerario",
                    "comp_nf_saida_manual",
                    "comp_nf_saida_markuprealtotal",
                    "comp_nf_saida_numeroempenho",
                    "comp_nf_saida_numpedprodrel",
                    "comp_nf_saida_ordem",
                    "comp_nf_saida_unidadeexecutora",
                    "comp_nf_saida_valcustofrete",
                    "comp_nf_saida_valoricmsdispensado",
                    "comp_nf_saida_aidf",
                    "comp_nf_saida_observacao",
                    "comp_nf_saida_recibonfe",
                    "comp_nf_saida_chavedeacessonfe",
                    "comp_nf_saida_situacaonfe",
                    "comp_nf_saida_numeroprotocolo",
                    "comp_nf_saida_codigonfe",
                    "comp_nf_saida_lotenfe",
                    "comp_nf_saida_justificativa",
                    "comp_nf_saida_flagemitcontingencia",
                    "comp_nf_saida_filialnfe",
                    "comp_nf_saida_finnfe",
                    "comp_nf_saida_numordcontingencia",
                    "comp_nf_saida_numeroprotocolocancelamento",
                    "comp_nf_saida_numeroprotocoloinutilizacao",
                    "comp_nf_saida_recibodpec",
                    "comp_nf_saida_dtemis",
                    "comp_nf_saida_dhprotocolo",
                    "comp_nf_saida_dhrecibodpec",
                    "comp_nf_saida_dhcancelamento",
                    "comp_nf_saida_redzmanual",
                    "comp_nf_saida_flagpiscofins",
                    "comp_nf_saida_valoracrescimo",
                    "comp_nf_saida_ade_atodeclaratorio",
                    "comp_nf_saida_ade_datadocumento",
                    "comp_nf_saida_ade_modelodocumento",
                    "comp_nf_saida_ade_numerodocumento",
                    "comp_nf_saida_ade_participante",
                    "comp_nf_saida_ade_seriedocumento",
                    "comp_nf_saida_codproconj",
                    "comp_nf_saida_descontodevolucao",
                    "comp_nf_saida_descontosuframa",
                    "comp_nf_saida_etiquetaemitida",
                    "comp_nf_saida_flagpesoalterado",
                    "comp_nf_saida_isscidade",
                    "comp_nf_saida_nfeimportada",
                    "comp_nf_saida_numpedautomatico",
                    "comp_nf_saida_oiddocdeorigemcomissao",
                    "comp_nf_saida_oiddocdeorigemfrete",
                    "comp_nf_saida_percentualcomissao",
                    "comp_nf_saida_quantconj",
                    "comp_nf_saida_ratendimento",
                    "comp_nf_saida_recebimentotef",
                    "comp_nf_saida_usulibcancelamentonf",
                    "comp_nf_saida_valoricmfreteo",
                    "comp_nf_saida_totaltributo",
                    "comp_nf_saida_dhemissao",
                    "comp_nf_saida_cod_inf_compl",
                    "comp_nf_saida_des_inf_compl",
                    "comp_nf_saida_flagrentabi",
                    "comp_nf_saida_valordescontopiscofins",
                    "comp_nf_saida_flagcriacao",
                    "comp_nf_saida_dhinutilizaþòo",
                    "comp_nf_saida_chavecancelamentocfe",
                    "comp_nf_saida_regimeespecial",
                    "comp_nf_saida_fimfaixainutilizacao",
                    "comp_nf_saida_dhcontingencia",
                    "comp_nf_saida_justificativacontingencia",
                    "comp_nf_saida_filialusuario",
                    "comp_nf_saida_rusuariocriacao",
                    "comp_nf_saida_predanfe",
                    "comp_nf_saida_linkimagemcanhoto",
                    "comp_nf_saida_entradaautomatica",
                    "comp_nf_saida_entradaorigem",
                    "comp_nf_saida_flagdespinclusanaotributada",
                    "comp_nf_saida_enviadomensagem",
                    "comp_nf_saida_dhinutilizacao",
                    "last_operation",
                    "last_commit_time"
        ]);
    }

}
