<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('notas_fiscais', function (Blueprint $table) {
            $table->id();
            $table->string("numnota", 13)->nullable(true);
            $table->string("serie", 3)->nullable(true);
            $table->string("espdoc", 3)->nullable(true);
            $table->string("filial", 2)->nullable(true);
            $table->string("estado", 2)->nullable(true);
            $table->string("cfo", 4)->nullable(true);
            $table->string("tpo", 30)->nullable(true);
            $table->string("destaqipi", 1)->nullable(true);
            $table->string("freteinc", 1)->nullable(true);
            $table->string("ccusto", 5)->nullable(true);
            $table->string("obs", 20)->nullable(true);
            $table->string("codvend", 5)->nullable(true);
            $table->string("codmetra", 2)->nullable(true);
            $table->string("codtran", 3)->nullable(true);
            $table->string("icmsipi", 1)->nullable(true);
            $table->string("codrote", 2)->nullable(true);
            $table->string("filtransf", 2)->nullable(true);
            $table->string("tiponf", 2)->nullable(true);
            $table->string("codsitest", 5)->nullable(true);
            $table->string("codsitfed", 5)->nullable(true);
            $table->string("cus", 1)->nullable(true);
            $table->string("modelonf", 2)->nullable(true);
            $table->string("est", 1)->nullable(true);
            $table->string("codmes", 2)->nullable(true);
            $table->string("codtran2", 3)->nullable(true);
            $table->string("cupomini", 6)->nullable(true);
            $table->string("cupomfim", 6)->nullable(true);
            $table->string("clasvend", 2)->nullable(true);
            $table->string("pedimpo", 8)->nullable(true);
            $table->string("tiponota", 1)->nullable(true);
            $table->string("numecf", 3)->nullable(true);
            $table->string("numcupon", 4)->nullable(true);
            $table->string("numnfecf", 6)->nullable(true);
            $table->string("TipoEntr", 1)->nullable(true);
            $table->string("codlis", 2)->nullable(true);
            $table->string("deporigem", 2)->nullable(true);
            $table->string("contredz", 6)->nullable(true);
            $table->string("codger", 5)->nullable(true);
            $table->string("Historico", 254)->nullable(true);
            $table->string("SerieECF", 20)->nullable(true);
            $table->string("ContReiOpe", 3)->nullable(true);
            $table->dateTime("dtemis")->nullable(true);
            $table->dateTime("dtcancel")->nullable(true);
            $table->double("valcontab")->nullable(true);
            $table->double("baseicm")->nullable(true);
            $table->double("baseicm2")->nullable(true);
            $table->double("baseicm3")->nullable(true);
            $table->double("alqicm")->nullable(true);
            $table->double("alqicm2")->nullable(true);
            $table->double("alqicm3")->nullable(true);
            $table->double("valicm")->nullable(true);
            $table->double("valicm2")->nullable(true);
            $table->double("valicm3")->nullable(true);
            $table->double("baseipi")->nullable(true);
            $table->double("valipi")->nullable(true);
            $table->double("valsemicm")->nullable(true);
            $table->double("valsemipi")->nullable(true);
            $table->double("basestrib")->nullable(true);
            $table->double("valsubstri")->nullable(true);
            $table->double("valtribdif")->nullable(true);
            $table->double("valservico")->nullable(true);
            $table->double("valiss")->nullable(true);
            $table->double("valfrete")->nullable(true);
            $table->double("valseguro")->nullable(true);
            $table->double("outricm")->nullable(true);
            $table->double("outripi")->nullable(true);
            $table->double("valentrad")->nullable(true);
            $table->double("desconto")->nullable(true);
            $table->double("comissao")->nullable(true);
            $table->double("valemba")->nullable(true);
            $table->double("percsubst")->nullable(true);
            $table->double("lucro")->nullable(true);
            $table->double("baseiss")->nullable(true);
            $table->double("peripi")->nullable(true);
            $table->double("baseicm4")->nullable(true);
            $table->double("alqicm4")->nullable(true);
            $table->double("valicm4")->nullable(true);
            $table->double("valnfche")->nullable(true);
            $table->double("baseicm5")->nullable(true);
            $table->double("alqicm5")->nullable(true);
            $table->double("valicm5")->nullable(true);
            $table->double("BaseINSS")->nullable(true);
            $table->double("AliqINSS")->nullable(true);
            $table->double("ValINSS")->nullable(true);
            $table->double("AliqISSRet")->nullable(true);
            $table->double("BaseISSRet")->nullable(true);
            $table->double("ValISSRet")->nullable(true);
            $table->double("ValIRRF")->nullable(true);
            $table->double("NFFutura")->nullable(true);
            $table->double("faturado")->nullable(true);
            $table->double("atualiz")->nullable(true);
            $table->double("flagemit")->nullable(true);
            $table->double("flagregfis")->nullable(true);
            $table->double("flagatua")->nullable(true);
            $table->double("flaginter")->nullable(true);
            $table->double("flagcontab")->nullable(true);
            $table->double("rec")->nullable(true);
            $table->double("cxa")->nullable(true);
            $table->double("flu")->nullable(true);
            $table->double("ctb")->nullable(true);
            $table->double("atf")->nullable(true);
            $table->double("integrado")->nullable(true);
            $table->double("lif")->nullable(true);
            $table->double("fat")->nullable(true);
            $table->double("exportado")->nullable(true);
            $table->double("gve")->nullable(true);
            $table->double("flagcons")->nullable(true);
            $table->double("exporta")->nullable(true);
            $table->double("impoger")->nullable(true);
            $table->double("icmsfonte")->nullable(true);
            $table->double("totmerc")->nullable(true);
            $table->double("totpeso")->nullable(true);
            $table->double("txfinan")->nullable(true);
            $table->double("exced")->nullable(true);
            $table->double("atuacum")->nullable(true);
            $table->double("jacomis")->nullable(true);
            $table->double("Contabilizado")->nullable(true);
            $table->double("gt")->nullable(true);
            $table->double("BaseIR")->nullable(true);
            $table->double("AliqIR")->nullable(true);
            $table->double("validade")->nullable(true);
            $table->double("sitproduto")->nullable(true);
            $table->double("DESPNAOINCLUSAS")->nullable(true);
            $table->double("ICMSDESPNAOINCLUSAS")->nullable(true);
            $table->double("FRETESUBSTRIBUTARIA")->nullable(true);
            $table->double("GTFim")->nullable(true);
            $table->double("ValCanECF")->nullable(true);
            $table->double("ValDescECF")->nullable(true);
            $table->double("OUTRASDESPESASINCLUSAS")->nullable(true);
            $table->double("TOTALPRECOCOMICMS")->nullable(true);
            $table->double("TOTALVALORICMS")->nullable(true);
            $table->double("DESPESASIMPORTACAO")->nullable(true);
            $table->string("pedido_id", 100)->nullable(true);
            $table->integer("numped")->nullable(true);
            $table->integer("codnatop")->nullable(true);
            $table->integer("localporta")->nullable(true);
            $table->integer("conta")->nullable(true);
            $table->integer("oiddocdeorigem")->nullable(true);
            $table->integer("codforout")->nullable(true);
            $table->integer("tpooutraent")->nullable(true);
            $table->integer("OIDREVENDA")->nullable(true);
            $table->integer("NOrdExpedic")->nullable(true);
            $table->integer("NUMORDECF")->nullable(true);
            $table->integer("oidserialecf")->nullable(true);
            $table->integer("codclie")->nullable(true);
            $table->integer("numord"); //chave unique
            $table->integer("condpag")->nullable(true);
            $table->integer("clifim")->nullable(true);
            $table->integer("clientea")->nullable(true);
            $table->integer("nordven")->nullable(true);
            $table->integer("numordfis")->nullable(true);
            
            //campos do COMPLEMENTONFSAIDA
            $table->string("comp_nf_saida_expedidor", 30)->nullable(true);
            $table->string("comp_nf_saida_motorista", 30)->nullable(true);
            $table->string("comp_nf_saida_placa", 8)->nullable(true);
            $table->string("comp_nf_saida_responsavelconsulta", 254)->nullable(true);
            $table->string("comp_nf_saida_tipofrete", 1)->nullable(true);
            $table->string("comp_nf_saida_classe", 10)->nullable(true);
            $table->string("comp_nf_saida_codvendext", 5)->nullable(true);
            $table->string("comp_nf_saida_numeroempenho", 40)->nullable(true);
            $table->string("comp_nf_saida_unidadeexecutora", 40)->nullable(true);
            $table->string("comp_nf_saida_aidf", 11)->nullable(true);
            $table->string("comp_nf_saida_observacao", 254)->nullable(true);
            $table->string("comp_nf_saida_chavedeacessonfe", 44)->nullable(true);
            $table->string("comp_nf_saida_situacaonfe", 2)->nullable(true);
            $table->string("comp_nf_saida_lotenfe", 15)->nullable(true);
            $table->string("comp_nf_saida_justificativa", 254)->nullable(true);
            $table->string("comp_nf_saida_filialnfe", 2)->nullable(true);
            $table->string("comp_nf_saida_recibodpec", 35)->nullable(true);
            $table->string("comp_nf_saida_ade_atodeclaratorio", 50)->nullable(true);
            $table->string("comp_nf_saida_ade_modelodocumento", 2)->nullable(true);
            $table->string("comp_nf_saida_ade_numerodocumento", 9)->nullable(true);
            $table->string("comp_nf_saida_ade_participante", 14)->nullable(true);
            $table->string("comp_nf_saida_ade_seriedocumento", 5)->nullable(true);
            $table->string("comp_nf_saida_codproconj", 5)->nullable(true);
            $table->string("comp_nf_saida_nfeimportada", 20)->nullable(true);
            $table->string("comp_nf_saida_ratendimento", 254)->nullable(true);
            $table->string("comp_nf_saida_cod_inf_compl", 6)->nullable(true);
            $table->string("comp_nf_saida_des_inf_compl", 254)->nullable(true);
            $table->string("comp_nf_saida_chavecancelamentocfe", 44)->nullable(true);
            $table->string("comp_nf_saida_justificativacontingencia", 254)->nullable(true);
            $table->string("comp_nf_saida_filialusuario", 2)->nullable(true);
            $table->string("comp_nf_saida_linkimagemcanhoto", 254)->nullable(true);
            $table->integer("comp_nf_saida_gerarnfservico")->nullable(true);
            $table->integer("comp_nf_saida_moeda")->nullable(true);
            $table->integer("comp_nf_saida_numordnfvenda")->nullable(true);
            $table->integer("comp_nf_saida_numordprodproprio")->nullable(true);
            $table->integer("comp_nf_saida_numpedregional")->nullable(true);
            $table->integer("comp_nf_saida_oidcontratante")->nullable(true);
            $table->integer("comp_nf_saida_itinerario")->nullable(true);
            $table->integer("comp_nf_saida_manual")->nullable(true);
            $table->integer("comp_nf_saida_numpedprodrel")->nullable(true);
            $table->integer("comp_nf_saida_ordem")->nullable(true);
            $table->integer("comp_nf_saida_numordcontingencia")->nullable(true);
            $table->integer("comp_nf_saida_numpedautomatico")->nullable(true);
            $table->integer("comp_nf_saida_oiddocdeorigemcomissao")->nullable(true);
            $table->integer("comp_nf_saida_oiddocdeorigemfrete")->nullable(true);
            $table->integer("comp_nf_saida_usulibcancelamentonf")->nullable(true);
            $table->integer("comp_nf_saida_regimeespecial")->nullable(true);
            $table->integer("comp_nf_saida_rusuariocriacao")->nullable(true);
            $table->integer("comp_nf_saida_entradaautomatica")->nullable(true);
            $table->integer("comp_nf_saida_entradaorigem")->nullable(true);
            $table->integer("comp_nf_saida_enviadomensagem")->nullable(true);
            $table->double("comp_nf_saida_baseicmdestacado")->nullable(true);
            $table->double("comp_nf_saida_codigoregiao")->nullable(true);
            $table->double("comp_nf_saida_cotacaomoeda")->nullable(true);
            $table->double("comp_nf_saida_fretepagar")->nullable(true);
            $table->double("comp_nf_saida_kmatual")->nullable(true);
            $table->double("comp_nf_saida_kmmes")->nullable(true);
            $table->double("comp_nf_saida_percentualcofins")->nullable(true);
            $table->double("comp_nf_saida_percentualpis")->nullable(true);
            $table->double("comp_nf_saida_percicmdestacado")->nullable(true);
            $table->double("comp_nf_saida_situacaocadastrosuframa")->nullable(true);
            $table->double("comp_nf_saida_statusconsignacao")->nullable(true);
            $table->double("comp_nf_saida_valorfretedestacado")->nullable(true);
            $table->double("comp_nf_saida_valoricmfrete")->nullable(true);
            $table->double("comp_nf_saida_markuprealtotal")->nullable(true);
            $table->double("comp_nf_saida_valcustofrete")->nullable(true);
            $table->double("comp_nf_saida_valoricmsdispensado")->nullable(true);
            $table->double("comp_nf_saida_recibonfe")->nullable(true);
            $table->double("comp_nf_saida_numeroprotocolo")->nullable(true);
            $table->double("comp_nf_saida_codigonfe")->nullable(true);
            $table->double("comp_nf_saida_flagemitcontingencia")->nullable(true);
            $table->double("comp_nf_saida_finnfe")->nullable(true);
            $table->double("comp_nf_saida_numeroprotocolocancelamento")->nullable(true);
            $table->double("comp_nf_saida_numeroprotocoloinutilizacao")->nullable(true);
            $table->double("comp_nf_saida_redzmanual")->nullable(true);
            $table->double("comp_nf_saida_flagpiscofins")->nullable(true);
            $table->double("comp_nf_saida_valoracrescimo")->nullable(true);
            $table->double("comp_nf_saida_descontodevolucao")->nullable(true);
            $table->double("comp_nf_saida_descontosuframa")->nullable(true);
            $table->double("comp_nf_saida_etiquetaemitida")->nullable(true);
            $table->double("comp_nf_saida_flagpesoalterado")->nullable(true);
            $table->double("comp_nf_saida_isscidade")->nullable(true);
            $table->double("comp_nf_saida_percentualcomissao")->nullable(true);
            $table->double("comp_nf_saida_quantconj")->nullable(true);
            $table->double("comp_nf_saida_recebimentotef")->nullable(true);
            $table->double("comp_nf_saida_valoricmfreteo")->nullable(true);
            $table->double("comp_nf_saida_totaltributo")->nullable(true);
            $table->double("comp_nf_saida_flagrentabi")->nullable(true);
            $table->double("comp_nf_saida_valordescontopiscofins")->nullable(true);
            $table->double("comp_nf_saida_flagcriacao")->nullable(true);
            $table->double("comp_nf_saida_fimfaixainutilizacao")->nullable(true);
            $table->double("comp_nf_saida_predanfe")->nullable(true);
            $table->double("comp_nf_saida_flagdespinclusanaotributada")->nullable(true);
            $table->datetime("comp_nf_saida_consultasuframa")->nullable(true);
            $table->datetime("comp_nf_saida_previsaoentrega")->nullable(true);
            $table->datetime("comp_nf_saida_dtemis")->nullable(true);
            $table->datetime("comp_nf_saida_dhprotocolo")->nullable(true);
            $table->datetime("comp_nf_saida_dhrecibodpec")->nullable(true);
            $table->datetime("comp_nf_saida_dhcancelamento")->nullable(true);
            $table->datetime("comp_nf_saida_ade_datadocumento")->nullable(true);
            $table->datetime("comp_nf_saida_dhemissao")->nullable(true);
            $table->datetime("comp_nf_saida_dhinutilizaþòo")->nullable(true);
            $table->datetime("comp_nf_saida_dhcontingencia")->nullable(true);
            $table->datetime("comp_nf_saida_dhinutilizacao")->nullable(true);

            $table->unique(array('numord'));

            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->nullable()->useCurrentOnUpdate();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('notas_fiscais');
    }
};