SELECT
    ct.numped,
    p.codclie,
    p.numorc,
    p.codvend,
    p.valped,
    p.valentrad,
    p.desconto,
    p.dtprevent,
    p.condpag,
    p.dtpripag,
    p.dtpedido,
    p.obs,
    p.numord,
    p.tpo,
    ct.filial,
    p.referencia,
    CASE
        WHEN (p.referencia is not null) AND (p.referencia <> '') AND (p.referencia <> ' ')  
            THEN p.referencia
        ELSE CAST(ct.numped AS VARCHAR(100))
    END AS pedido_id,
    p.moedcor,
    p.dataatu,
    p.ordprod,
    p.perfrete,
    p.valfrete,
    p.perseguro,
    p.valseguro,
    TRIM(p.razaocli) as razaocli,
    TRIM(p.endercli) AS endercli,
    TRIM(p.bairrcli) as bairrcli,
    TRIM(p.cidadcli) as cidadcli,
    TRIM(p.cepcli) AS cepcli,
    REPLACE(REPLACE(REPLACE(TRIM(p.cgccli),'.', ''),'-', ''),'/', '') as cpf_cnpj,
    TRIM(p.inscli) as inscli,
    TRIM(p.estcli) AS estcli,
    p.tipnota,
    p.codtran,
    p.codtran2,
    p.codendent,
    p.codendcob,
    p.observ,
    p.filialcli,
    p.respcli,
    p.respfor,
    p.tpoent,
    p.situacao,
    p.numpedfil,
    p.atuarec,
    p.numrom,
    p.pendente,
    p.libdesc,
    p.libcred,
    p.liblimi,
    p.libbloq,
    p.libatra,
    p.sitven,
    p.naoaprov,
    TRIM(p.telecli) as telecli,
    p.horaped,
    p.freteorc,
    p.numfrete,
    p.usucred,
    p.credito,
    p.libform,
    p.rformadepagar,
    p.codlis,
    p.tipofrete,
    p.codrote,
    p.SitConf,
    TRIM(p.NumClie) as NumClie,
    p.ContribClie,
    p.FilialVend,
    p.destino,
    p.CodMens,
    p.Tributado,
    p.inscsufracli,
    TRIM(p.COMPLCLI) AS COMPLCLI,
    p.sitmanut,
    p.codforout,
    p.deporigem,
    p.tpooutraent,
    p.Cqualidade,
    p.Refqualidade,
    p.condpagposterior,
    p.Etapa,
    p.valorfat,
    p.valorrec,
    p.taxanf,
    p.receber,
    p.tipovenda,
    p.oidrevenda,
    p.sitmon,
    p.temconjunto,
    p.txrevenda,
    p.SitCred,
    p.FlagEmit,
    p.sitsaga,
    p.dtvalidade,
    p.oidcontato,
    p.LIBTPDOC,
    p.Apelido,
    TRIM(p.contato) AS contato,
    p.PerDescto,
    p.reservaconjunto,
    p.viamont,
    p.TemSeguro,
    p.PLANOSEMJUROS,
    p.rcarenciaparcela,
    p.rdocplano,
    p.rdocentrada,
    p.ARQUIVOCDL,
    p.FatorEmpresa,
    p.Urgente,
    p.PERCIPISEGURO,
    p.OUTRASDESPESASINCLUSAS,
    p.libmarkmin,
    p.VIAORCAMENTO,
    p.ViaOrdemSeparacao,
    p.LIBPRAZOMEDIO,
    p.LIBFRETE,
    p.prazomedio,
    p.desmembrado,
    p.VALPEDTX,
    p.ORGAOPUBCLIE,
    p.ENDERECOFATURA,
    p.CONTRATO,
    p.EMPENHO,
    TRIM(cli.nome) AS nome_cliente,
    TRIM(lower((select top 1 co.VALOR 
              from COMUNICACAO_V co 
              where co.RITEM = cli.oid and 
                   co.RTIPO = :rtipo))) as email_cliente,
    ct.SYS_CHANGE_OPERATION AS 'last_operation',
    COALESCE(tc.commit_time, GETDATE()) AS 'last_commit_time'
FROM CHANGETABLE (CHANGES [PEDICLICAD], :lastVersion) AS ct
LEFT JOIN sys.dm_tran_commit_table tc on ct.sys_change_version = tc.commit_ts
LEFT JOIN PEDICLICAD p on p.numped = ct.numped and p.filial = ct.filial
LEFT JOIN clientecad cli on cli.oid = p.codclie