
SELECT
    CONCAT(o.id, '-plataforma') as 'orcamento_id',
    CONCAT(o.id, '-plataforma') as 'idOrcamentoMdm',
    o.status ,
    o.prazo ,
    o.cupom_id ,
    o.motivo_perdido ,
    o.extra ,
    o.total as total_pedido,
    o.obs,
    o.info_adicionais ,
    o.origem_id ,
    o.orcamento_original ,
    o.area_venda_id ,
    o.ie_produtor_rural_id ,
    o.neurotech_status ,
    o.neurotech_user_id ,
    o.neurotech_data_acao,
    o.neurotech_data_duplicata ,
    o.neurotech_restricao_cadastral ,
    o.neurotech_restricao_externa ,
    o.neurotech_restricao_receita ,
    o.neurotech_vencidos ,
    o.neurotech_compras ,
    o.neurotech_vencer,
    o.created_at as orcamento_created_at,
    o.updated_at as orcamento_updated_at,
    co.users_id,
    co.cliente_id,
    co.ambientes_id,
    co.referencia,
    co.produto_id,
    co.qtd,
    co.caixa,
    co.de,
    co.preco,
    co.preco_desconto,
    co.desconto,
    co.total_desconto,
    co.peso_unitario,
    co.cupomid,
    co.codigo_cupom_id,
    co.frete_id,
    co.transportadora,
    co.frete,
    co.cep,
    co.estado,
    co.cidade,
    co.produto_gratis ,
    co.produto_tintometrico,
    co.codigo_cor_erp,
    co.codigo_cor_fabricante,
    co.cor_codigo_leque,
    co.cor_nome_leque,
    co.data_prevista,
    co.id_rota ,
    a.nome as nome_ambiente
FROM orcamentos o 
    INNER JOIN carrinho_orcamento co ON co.orcamento_id = o.id
    INNER JOIN ambientes a ON a .id = co.ambientes_id
WHERE ((o.updated_at is not null and o.updated_at >= :timeStamp) or (o.created_at >= :timeStampD))